services:
  postgres:
    image: postgres:15-alpine
    container_name: gocart-postgres
    env_file:
      - ../.env
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-gocart}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      POSTGRES_DB: ${POSTGRES_DB:-gocart}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  localstack:
    image: localstack/localstack
    container_name: gocart-localstack
    env_file:
      - ../.env
    ports:
      - "${LOCALSTACK_PORT:-4566}:4566"
    environment:
      - SERVICES=s3,sqs,sns
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-localstack}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-localstack}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME:-gocart}
      - AWS_S3_ENDPOINT=${AWS_S3_ENDPOINT:-http://localhost:4566}
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  postgres_data:
  localstack_data:
